# Copyright 2025 Paion Data. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  USER: QubitPi
  EMAIL: jack20220723@gmail.com
  NODE_VERSION: 22

jobs:
  cancel-previous:
    permissions:
      actions: write
    uses: ./.github/workflows/cancel-previous-run.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  yml-md-style-and-link-checks:
    uses: ./.github/workflows/yml-md-style-and-link-checks.yaml

  test-upversion:
    name: Test upversion.py
    needs: yml-md-style-and-link-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - run: echo "LAST_TAG=1.2.3" >> $GITHUB_ENV
      - run: |
          NEW_TAG=$(LAST_TAG=${LAST_TAG} python .github/version-bump/upversion.py)
          if [[ "$NEW_TAG" != "1.2.4" ]]; then
              exit 1
          fi

  docker-image:
    name: Build Test & Release Paion Data Docker Images
    needs: yml-md-style-and-link-checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-context: [
          {
            image-name: ubuntu-base,
            dockerfile-path: linuxserver/ubuntu
          },
          {
            image-name: react,
            dockerfile-path: linuxserver/react
          }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Test ${{ matrix.image-context.image-name }} image build
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image-context.dockerfile-path }}
          push: false
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: paiondatahub
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image-context.dockerfile-path }}
          push: true
          tags: paiondatahub/${{ matrix.image-context.image-name }}:latest
      - name: Push image Description
        if: github.ref == 'refs/heads/master'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: paiondatahub
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: paiondatahub/${{ matrix.image-context.image-name }}
          readme-filepath: ${{ matrix.image-context.dockerfile-path }}/README.md

  documentation:
    name: Test Documentation Build & Deploy Documentation to GitHub Pages
    needs: [test-upversion]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set up yarn
        run: |
          corepack enable
          yarn set version latest
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Load CNAME file
        if: github.ref == 'refs/heads/master'
        run: cp CNAME build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: ${{ env.USER }}
          user_email: ${{ env.EMAIL }}
